backend:
  name: github
  repo: cooder-it/studio21 #replace with your username/repo

media_folder: static/assets

collections:
  - name: projects
    label: Projekty
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
